### Configuración de Variables
@hostname = localhost
@port = 8000
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json

### 1. REGISTRO DE USUARIO
POST {{host}}/auth/registro
Content-Type: application/json

{
    "email": "admin@vinacoteca.cat",
    "password": "admin1vinoteca2"
}

###

### 2. LOGIN DE USUARIO
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "admin@vinacoteca.cat",
    "password": "admin1vinoteca2"
}

### 3. ACTUALIZAR PERFIL (Ruta Protegida)
# Importante: Copia el valor de "token" del login y pégalo aquí abajo
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Yjg2MGE4ZjgzOTA5MmVjMTQ1Y2NmMSIsImlhdCI6MTc3Mzc2Nzc2MiwiZXhwIjoxNzc0MzcyNTYyfQ.p_BukPPQUg54H5uv2GY1rDU62otrmA1xKM19rQpWFAk

PUT {{host}}/auth/perfil
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "nombre": "Marc Actualizado",
    "password": "nuevapassword123"
}

### 4. TEST LOGIN CON NUEVA PASSWORD
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "admin@vinacoteca.cat",
    "password": "nuevapassword123"
}

