### Configuración de Variables
@hostname = localhost
@port = 8000
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json

### 1. REGISTRO DE USUARIO
POST {{host}}/auth/registro
Content-Type: {{contentType}}

{
    "email": "admin@vinacoteca.cat",
    "password": "admin1vinoteca2",
    "rol": "admin"
}

### 2. LOGIN DE USUARIO
# @name login
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "admin@vinacoteca.cat",
    "password": "admin1vinoteca2"
}

### 3. ACTUALIZAR PERFIL
# Copia el token obtenido en el login aquí:
@token = 

PUT {{host}}/auth/perfil
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "nombre": "Marc Actualizado",
    "password": "nuevapassword123"
}

### --- SECCIÓN DE PRODUCTOS (Rutas de api/vino) ---

### 5. BIENVENIDA (Test Visual)
GET {{host}}/vino/

### 6. OBTENER TODOS LOS PRODUCTOS (Pública)
GET {{host}}/vino/todos

### 7. OBTENER UN PRODUCTO POR ID (Pública)
@vinoId = 69b9a52c704c98374c4aadab
GET {{host}}/vino/{{vinoId}}

### 8. CREAR UN NUEVO VINO (Protegida: Admin/Editor)
POST {{host}}/vino/
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "nombre": "Verde beti ",
    "descripcion": "Vino verde de bodegas de Sevilla.",
    "tipo_producto": "vino",
    "graduacion": 33.5,
    "precio": 75.00,
    "stock": 100,
    "detalles": {
        "bodega": "Heliopolis",
        "uva": "Uva de palmera",
        "tipo_vino": "Verde",
        "formato": "750ml"
    }
}

### 9. ACTUALIZAR UN PRODUCTO (Protegida: Admin/Editor)
PUT {{host}}/vino/{{vinoId}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{   
    "nombre": "Reserva DAW 2026",
    "precio": 49.99,
    "stock": 95,
    "detalles": {
        "bodega": "K-Lagan Vineyards",
        "uva": "BPA Noir modified"
    }
}

### 10. ELIMINAR UN PRODUCTO (Protegida: Admin/Editor)
DELETE {{host}}/vino/{{vinoId}}
Authorization: Bearer {{token}}